package com.assignments.q3;
/*
Q3. Inheritance
Write a java application to maintain information for xyz sports club. 
The sports club wants to store employee details, for each employee store 
id, name, mobile no, emailid, Department, designation, Date of joining. 
Employees are of 3 types: salaried employee, contract employee, vendors. 
If employee is salaried employee, then store basic salary. 
If it is contract employee then store no of hrs worked and per hour rate. 
If it is vendor then store no_of_employees, amount. 

Also store information about members of club. 
For each member store id, name, mobile no, emailid, type of membership, amount paid. 
For employee and members, id is autogenerated. 

Design a menu driven program to perform following: 
1. Display All employees (ask user salaried/contract/vendor, display only that type) 
2. Search by id 
3. Search by name 
4. Display all employees  
5. Calculate salary and display for all employees with particular designation 
6. Accept department from user and display 5 employees of that department. 
7. Exit

Salary formulas:
Salaried Employee: Basic + DA + HRA – PF 
   DA = 10% of basic 
   HRA = 15% of basic 
   PF = 12% of basic 
Contract Employee: Hr rate * no of hrs worked 
Vendor: amount + amount*18% GST
*/
/*
Base Employee class
Stores id, name, mobile, email, department, designation, date of joining.
Id is auto-generated.
*/
public abstract class Employee {
    private static int counter = 1;
    protected int id;
    protected String name, mobile, email, department, designation, doj;

    public Employee(String name, String mobile, String email, String dept, String desig, String doj) {
        this.id = counter++;
        this.name = name;
        this.mobile = mobile;
        this.email = email;
        this.department = dept;
        this.designation = desig;
        this.doj = doj;
    }

    public abstract double calculateSalary();

    public void display() {
        System.out.println("ID: " + id + ", Name: " + name +
                           ", Dept: " + department + ", Designation: " + designation +
                           ", DOJ: " + doj);
    }

    public int getId() { return id; }
    public String getName() { return name; }
    public String getDepartment() { return department; }
    public String getDesignation() { return designation; }
}
